[tool.poetry]
name = "pySigma-backend-databricks"
version = "0.1.0"
description = "pySigma databricks backend"
authors = ["Alex Ott <alexott@gmail.com>"]
license = "MIT"
repository = "https://github.com/alexott/pySigma-backend-databricks"
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = "^3.8"
pysigma = "^0.7.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
coverage = "^6.4.4"
sigma-cli = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
