title: AWS Config Disabling Channel/Recorder
id: 07330162-dba1-4746-8121-a9647d49d297
status: test
level: high
author: vitaliy0x1
description: Detects AWS Config Service disabling
references:
    - https://docs.aws.amazon.com/config/latest/developerguide/cloudtrail-log-files-for-aws-config.html
falsepositives:
    - Valid change in AWS Config Service
tags:
    - attack.defense-evasion
    - attack.t1562.001
date: '2020-01-21'
modified: '2022-10-09'
logsource:
    product: aws
    service: cloudtrail
detection:
    selection:
        eventSource: config.amazonaws.com
        eventName:
            - DeleteDeliveryChannel
            - StopConfigurationRecorder
    condition: selection
ocsf_mapping:
    class_name: file_activity
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: aws
            mapped_at: '2025-12-04T01:39:29.023492+00:00'
        service:
            source_field: service
            source_value: cloudtrail
            mapped_at: '2025-12-04T01:39:29.023492+00:00'
    detection_fields:
        -   source_field: eventSource
            target_table: file_activity
            target_field: metadata.product.name
            mapped_at: '2025-12-04T01:39:29.023515+00:00'
        -   source_field: eventName
            target_table: file_activity
            target_field: metadata.event_code
            mapped_at: '2025-12-04T01:39:29.023518+00:00'
