id: 636e30d5-3736-42ea-96b1-e6e2f8429fd6
title: Azure Owner Removed From Application or Service Principal
status: test
level: medium
description: Identifies when a owner is was removed from a application or service
    principal in Azure.
author: Austin Songer @austinsonger
date: '2021-09-03'
modified: '2022-10-09'
tags:
    - attack.defense-evasion
references:
    - https://learn.microsoft.com/en-us/entra/identity/monitoring-health/reference-audit-activities#application-proxy
falsepositives:
    - Owner being removed may be performed by a system administrator.
    - Verify whether the user identity, user agent, and/or hostname should be making
        changes in your environment.
    - Owner removed from unfamiliar users should be investigated. If known behavior
        is causing false positives, it can be exempted from the rule.
taxonomy: sigma
logsource:
    product: azure
    service: activitylogs
detection:
    selection:
        properties.message:
            - Remove owner from service principal
            - Remove owner from application
    condition: selection
ocsf_mapping:
    class_name: account_change
    activity_id: 6
    logsource:
        product:
            source_field: product
            source_value: azure
            mapped_at: '2025-11-26T02:20:57.893107+00:00'
        service:
            source_field: service
            source_value: activitylogs
            mapped_at: '2025-11-26T02:20:57.893107+00:00'
    detection_fields:
        -   source_field: properties.message
            target_table: account_change
            target_field: message
            mapped_at: '2025-11-26T02:20:57.893119+00:00'
