id: 7ee0b4aa-d8d4-4088-b661-20efdf41a04c
title: Azure Kubernetes Secret or Config Object Access
status: test
level: medium
description: Identifies when a Kubernetes account access a sensitive objects such
    as configmaps or secrets.
author: Austin Songer @austinsonger
date: '2021-08-07'
modified: '2022-08-23'
tags:
    - attack.impact
references:
    - https://learn.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftkubernetes
    - https://www.microsoft.com/security/blog/2021/03/23/secure-containerized-environments-with-updated-threat-matrix-for-kubernetes/
    - https://www.microsoft.com/security/blog/2020/04/02/attack-matrix-kubernetes/
    - https://medium.com/mitre-engenuity/att-ck-for-containers-now-available-4c2359654bf1
    - https://attack.mitre.org/matrices/enterprise/cloud/
falsepositives:
    - Sensitive objects may be accessed by a system administrator. Verify whether
        the user identity, user agent, and/or hostname should be making changes in
        your environment. Sensitive objects accessed from unfamiliar users should
        be investigated. If known behavior is causing false positives, it can be exempted
        from the rule.
taxonomy: sigma
logsource:
    product: azure
    service: activitylogs
detection:
    selection:
        operationName:
            - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/WRITE
            - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/DELETE
            - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/WRITE
            - MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/DELETE
    condition: selection
ocsf_mapping:
    class_name: entity_management
    activity_id: 2
    logsource:
        product:
            source_field: product
            source_value: azure
            mapped_at: '2025-11-26T02:21:04.471534+00:00'
        service:
            source_field: service
            source_value: activitylogs
            mapped_at: '2025-11-26T02:21:04.471534+00:00'
    detection_fields:
        -   source_field: operationName
            target_table: entity_management
            target_field: api.operation
            mapped_at: '2025-11-26T02:21:04.471546+00:00'
