title: Azure Application Security Group Modified or Deleted
id: 835747f1-9329-40b5-9cc3-97d465754ce6
status: test
level: medium
author: Austin Songer
description: Identifies when a application security group is modified or deleted.
references:
    - https://learn.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations
falsepositives:
    - Application security group being modified or deleted may be performed by a system
        administrator.
    - Verify whether the user identity, user agent, and/or hostname should be making
        changes in your environment.
    - Application security group modified or deleted from unfamiliar users should
        be investigated. If known behavior is causing false positives, it can be exempted
        from the rule.
tags:
    - attack.impact
date: '2021-08-16'
modified: '2022-08-23'
logsource:
    product: azure
    service: activitylogs
detection:
    selection:
        operationName:
            - MICROSOFT.NETWORK/APPLICATIONSECURITYGROUPS/WRITE
            - MICROSOFT.NETWORK/APPLICATIONSECURITYGROUPS/DELETE
    condition: selection
ocsf_mapping:
    class_name: entity_management
    activity_id: 3
    logsource:
        product:
            source_field: product
            source_value: azure
            mapped_at: '2025-12-04T01:38:28.154988+00:00'
        service:
            source_field: service
            source_value: activitylogs
            mapped_at: '2025-12-04T01:38:28.154988+00:00'
    detection_fields:
        -   source_field: operationName
            target_table: entity_management
            target_field: api.operation
            mapped_at: '2025-12-04T01:38:28.155004+00:00'
