title: Bitbucket Audit Log Configuration Updated
id: 6aa12161-235a-4dfb-9c74-fe08df8d8da1
status: test
level: medium
author: Muhammad Faisal (@faisalusuf)
description: Detects changes to the bitbucket audit log configuration.
references:
    - https://confluence.atlassian.com/bitbucketserver/view-and-configure-the-audit-log-776640417.html
falsepositives:
    - Legitimate user activity.
tags:
    - attack.defense-evasion
    - attack.t1562.001
date: '2024-02-25'
logsource:
    product: bitbucket
    service: audit
    definition: 'Requirements: "Basic" log level is required to receive these audit
        events.'
detection:
    selection:
        auditType.category: Auditing
        auditType.action: Audit log configuration updated
    condition: selection
ocsf_mapping:
    class_name: entity_management
    activity_id: 3
    logsource:
        product:
            source_field: product
            source_value: bitbucket
            mapped_at: '2025-12-04T01:39:36.771643+00:00'
        service:
            source_field: service
            source_value: audit
            mapped_at: '2025-12-04T01:39:36.771643+00:00'
    detection_fields:
        -   source_field: auditType.category
            target_table: entity_management
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:39:36.771657+00:00'
        -   source_field: auditType.action
            target_table: entity_management
            target_field: action
            mapped_at: '2025-12-04T01:39:36.771659+00:00'
