id: a9d4d3fa-8fc0-41bc-80b1-30b9fda79d6f
title: Remote Thread Created In Shell Application
status: experimental
level: medium
description: 'Detects remote thread creation in command shell applications, such as
    "Cmd.EXE" and "PowerShell.EXE".

    It is a common technique used by malware, such as IcedID, to inject malicious
    code and execute it within legitimate processes.

    '
author: Splunk Research Team
date: '2024-07-29'
tags:
    - attack.defense-evasion
    - attack.t1055
references:
    - https://research.splunk.com/endpoint/10399c1e-f51e-11eb-b920-acde48001122/
    - https://www.binarydefense.com/resources/blog/icedid-gziploader-analysis/
falsepositives:
    - Unknown
taxonomy: sigma
logsource:
    category: create_remote_thread
    product: windows
detection:
    selection:
        TargetImage|endswith:
            - \cmd.exe
            - \powershell.exe
            - \pwsh.exe
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: 4
    logsource:
        category:
            source_field: category
            source_value: create_remote_thread
            mapped_at: '2025-11-26T02:24:52.105344+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:24:52.105344+00:00'
    detection_fields:
        -   source_field: TargetImage
            target_table: process_activity
            target_field: process.file.path
            mapped_at: '2025-11-26T02:24:52.105391+00:00'
