id: 34986307-b7f4-49be-92f3-e7a4d01ac5db
title: Rclone Config File Creation
status: test
level: medium
description: Detects Rclone config files being created
author: Aaron Greetham (@beardofbinary) - NCC Group
date: '2021-05-26'
modified: '2023-05-09'
tags:
    - attack.exfiltration
    - attack.t1567.002
references:
    - https://research.nccgroup.com/2021/05/27/detecting-rclone-an-effective-tool-for-exfiltration/
falsepositives:
    - Legitimate Rclone usage
taxonomy: sigma
logsource:
    category: file_event
    product: windows
detection:
    selection:
        TargetFilename|contains|all:
            - :\Users\
            - \.config\rclone\
    condition: selection
ocsf_mapping:
    class_name: file_activity
    logsource:
        category:
            source_field: category
            source_value: file_event
            mapped_at: '2025-11-13T20:21:34.620786+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:21:34.620786+00:00'
    detection_fields:
        -   source_field: TargetFilename
            target_table: file_activity
            target_field: file.path
            mapped_at: '2025-11-13T20:21:34.620790+00:00'
