id: 41bb431f-56d8-4691-bb56-ed34e390906f
title: UAC Bypass Using MSConfig Token Modification - File
status: test
level: high
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
author: Christian Burkard (Nextron Systems)
date: '2021-08-30'
modified: '2022-10-09'
tags:
    - attack.defense-evasion
    - attack.privilege-escalation
    - attack.t1548.002
references:
    - https://github.com/hfiref0x/UACME
falsepositives:
    - Unknown
taxonomy: sigma
logsource:
    category: file_event
    product: windows
detection:
    selection:
        TargetFilename|startswith: C:\Users\
        TargetFilename|endswith: \AppData\Local\Temp\pkgmgr.exe
    condition: selection
ocsf_mapping:
    class_name: file_activity
    logsource:
        category:
            source_field: category
            source_value: file_event
            mapped_at: '2025-11-13T20:21:36.276317+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:21:36.276317+00:00'
    detection_fields:
        -   source_field: TargetFilename
            target_table: file_activity
            target_field: file.path
            mapped_at: '2025-11-13T20:21:36.276323+00:00'
