id: ee2803f0-71c8-4831-b48b-a1fc57601ee4
title: Google Workspace Application Removed
status: test
level: medium
description: Detects when an an application is removed from Google Workspace.
author: Austin Songer
date: '2021-08-26'
modified: '2023-10-11'
tags:
    - attack.impact
references:
    - https://cloud.google.com/logging/docs/audit/gsuite-audit-logging#3
    - https://developers.google.com/admin-sdk/reports/v1/appendix/activity/admin-domain-settings?hl=en#REMOVE_APPLICATION
    - https://developers.google.com/admin-sdk/reports/v1/appendix/activity/admin-domain-settings?hl=en#REMOVE_APPLICATION_FROM_WHITELIST
falsepositives:
    - Application being removed may be performed by a System Administrator.
taxonomy: sigma
logsource:
    product: gcp
    service: google_workspace.admin
detection:
    selection:
        eventService: admin.googleapis.com
        eventName:
            - REMOVE_APPLICATION
            - REMOVE_APPLICATION_FROM_WHITELIST
    condition: selection
ocsf_mapping:
    class_name: entity_management
    logsource:
        product:
            source_field: product
            source_value: gcp
            mapped_at: '2025-11-13T20:17:41.577488+00:00'
        service:
            source_field: service
            source_value: google_workspace.admin
            mapped_at: '2025-11-13T20:17:41.577488+00:00'
    detection_fields:
        -   source_field: eventService
            target_table: entity_management
            target_field: <UNMAPPED>
            mapped_at: '2025-11-13T20:17:42.509046+00:00'
        -   source_field: eventName
            target_table: entity_management
            target_field: action
            mapped_at: '2025-11-13T20:17:42.509070+00:00'
