title: Github SSH Certificate Configuration Changed
id: 2f575940-d85e-4ddc-af13-17dad6f1a0ef
status: experimental
level: medium
author: Romain Gaillard (@romain-gaillard)
description: Detects when changes are made to the SSH certificate configuration of
    the organization.
references:
    - https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-git-access-to-your-organizations-repositories/about-ssh-certificate-authorities
    - https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise#ssh_certificate_authority
falsepositives:
    - Allowed administrative activities.
tags:
    - attack.persistence
    - attack.privilege-escalation
    - attack.t1078.004
date: '2024-07-29'
logsource:
    product: github
    service: audit
    definition: 'Requirements: The audit log streaming feature must be enabled to
        be able to receive such logs. You can enable following the documentation here:
        https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise#setting-up-audit-log-streaming'
detection:
    selection:
        action:
            - ssh_certificate_authority.create
            - ssh_certificate_requirement.disable
    condition: selection
ocsf_mapping:
    class_name: vulnerability_finding
    activity_id: 2
    logsource:
        product:
            source_field: product
            source_value: github
            mapped_at: '2025-12-04T01:37:01.140725+00:00'
        service:
            source_field: service
            source_value: audit
            mapped_at: '2025-12-04T01:37:01.140725+00:00'
    detection_fields:
        -   source_field: action
            target_table: vulnerability_finding
            target_field: action
            mapped_at: '2025-12-04T01:37:01.140737+00:00'
