id: 977ef627-4539-4875-adf4-ed8f780c4922
title: Auditing Configuration Changes on Linux Host
status: test
level: high
description: Detect changes in auditd configuration files
author: Mikhail Larin, oscd.community
date: '2019-10-25'
modified: '2021-11-27'
tags:
    - attack.defense-evasion
    - attack.t1562.006
references:
    - https://github.com/Neo23x0/auditd/blob/master/audit.rules
    - Self Experience
fields:
    - exe
    - comm
    - key
falsepositives:
    - Legitimate administrative activity
taxonomy: sigma
logsource:
    product: linux
    service: auditd
detection:
    selection:
        type: PATH
        name:
            - /etc/audit/*
            - /etc/libaudit.conf
            - /etc/audisp/*
    condition: selection
ocsf_mapping:
    class_name: file_activity
    logsource:
        product:
            source_field: product
            source_value: linux
            mapped_at: '2025-11-13T20:15:24.711892+00:00'
        service:
            source_field: service
            source_value: auditd
            mapped_at: '2025-11-13T20:15:24.711892+00:00'
    detection_fields:
        -   source_field: type
            target_table: file_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-13T20:15:24.711909+00:00'
        -   source_field: name
            target_table: file_activity
            target_field: file.name
            mapped_at: '2025-11-13T20:15:24.711912+00:00'
