title: Auditing Configuration Changes on Linux Host
id: 977ef627-4539-4875-adf4-ed8f780c4922
status: test
level: high
author: Mikhail Larin, oscd.community
description: Detect changes in auditd configuration files
references:
    - https://github.com/Neo23x0/auditd/blob/master/audit.rules
    - Self Experience
fields:
    - exe
    - comm
    - key
falsepositives:
    - Legitimate administrative activity
tags:
    - attack.defense-evasion
    - attack.t1562.006
date: '2019-10-25'
modified: '2021-11-27'
logsource:
    product: linux
    service: auditd
detection:
    selection:
        type: PATH
        name:
            - /etc/audit/*
            - /etc/libaudit.conf
            - /etc/audisp/*
    condition: selection
ocsf_mapping:
    class_name: file_activity
    activity_id: 3
    logsource:
        product:
            source_field: product
            source_value: linux
            mapped_at: '2025-12-04T01:35:32.133877+00:00'
        service:
            source_field: service
            source_value: auditd
            mapped_at: '2025-12-04T01:35:32.133877+00:00'
    detection_fields:
        -   source_field: type
            target_table: file_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:35:32.133918+00:00'
        -   source_field: name
            target_table: file_activity
            target_field: file.name
            mapped_at: '2025-12-04T01:35:32.133923+00:00'
