title: Logging Configuration Changes on Linux Host
id: c830f15d-6f6e-430f-8074-6f73d6807841
status: test
level: high
author: Mikhail Larin, oscd.community
description: Detect changes of syslog daemons configuration files
references:
    - self experience
fields:
    - exe
    - comm
    - key
falsepositives:
    - Legitimate administrative activity
tags:
    - attack.defense-evasion
    - attack.t1562.006
date: '2019-10-25'
modified: '2021-11-27'
logsource:
    product: linux
    service: auditd
detection:
    selection:
        type: PATH
        name:
            - /etc/syslog.conf
            - /etc/rsyslog.conf
            - /etc/syslog-ng/syslog-ng.conf
    condition: selection
ocsf_mapping:
    class_name: file_activity
    activity_id: 3
    logsource:
        product:
            source_field: product
            source_value: linux
            mapped_at: '2025-12-04T01:35:39.744082+00:00'
        service:
            source_field: service
            source_value: auditd
            mapped_at: '2025-12-04T01:35:39.744082+00:00'
    detection_fields:
        -   source_field: type
            target_table: file_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:35:39.744094+00:00'
        -   source_field: name
            target_table: file_activity
            target_field: file.name
            mapped_at: '2025-12-04T01:35:39.744100+00:00'
