title: Okta Application Modified or Deleted
id: 7899144b-e416-4c28-b0b5-ab8f9e0a541d
status: test
level: medium
author: Austin Songer @austinsonger
description: Detects when an application is modified or deleted.
references:
    - https://developer.okta.com/docs/reference/api/system-log/
    - https://developer.okta.com/docs/reference/api/event-types/
falsepositives:
    - Unknown
tags:
    - attack.impact
date: '2021-09-12'
modified: '2022-10-09'
logsource:
    product: okta
    service: okta
detection:
    selection:
        eventtype:
            - application.lifecycle.update
            - application.lifecycle.delete
    condition: selection
ocsf_mapping:
    class_name: account_change
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: okta
            mapped_at: '2025-12-04T01:37:15.837118+00:00'
        service:
            source_field: service
            source_value: okta
            mapped_at: '2025-12-04T01:37:15.837118+00:00'
    detection_fields:
        -   source_field: eventtype
            target_table: account_change
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:37:15.837134+00:00'
