title: Modify Group Policy Settings - ScriptBlockLogging
id: b7216a7d-687e-4c8d-82b1-3080b2ad961f
status: test
level: medium
author: frack113
description: Detect malicious GPO modifications can be used to implement many other
    malicious behaviors.
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/40b77d63808dd4f4eafb83949805636735a1fd15/atomics/T1484.001/T1484.001.md
falsepositives:
    - Legitimate use
tags:
    - attack.defense-evasion
    - attack.privilege-escalation
    - attack.t1484.001
date: '2022-08-19'
logsource:
    category: ps_script
    product: windows
    definition: 'Requirements: Script Block Logging must be enabled'
detection:
    selection_path:
        ScriptBlockText|contains: \SOFTWARE\Policies\Microsoft\Windows\System
    selection_key:
        ScriptBlockText|contains:
            - GroupPolicyRefreshTimeDC
            - GroupPolicyRefreshTimeOffsetDC
            - GroupPolicyRefreshTime
            - GroupPolicyRefreshTimeOffset
            - EnableSmartScreen
            - ShellSmartScreenLevel
    condition: all of selection_*
related:
    -   id: ada4b0c4-758b-46ac-9033-9004613a150d
        type: similar
ocsf_mapping:
    class_name: script_activity
    activity_id: <UNMAPPED>
    logsource:
        category:
            source_field: category
            source_value: ps_script
            mapped_at: '2025-12-04T01:53:43.948620+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:53:43.948620+00:00'
    detection_fields:
        -   source_field: ScriptBlockText
            target_table: script_activity
            target_field: script.script_content.value
            mapped_at: '2025-12-04T01:53:43.948635+00:00'
