id: b53317a0-8acf-4fd1-8de8-a5401e776b96
title: Application Removed Via Wmic.EXE
status: test
level: medium
description: Detects the removal or uninstallation of an application via "Wmic.EXE".
author: frack113
date: '2022-01-28'
modified: '2024-07-02'
tags:
    - attack.execution
    - attack.t1047
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
falsepositives:
    - Unknown
related: 'SigmaRelated(related=[SigmaRelatedItem(id=UUID(''847d5ff3-8a31-4737-a970-aeae8fe21765''),
    type=<SigmaRelatedType.DERIVED: 2>)])'
taxonomy: sigma
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        Image|endswith: \WMIC.exe
        OriginalFileName: wmic.exe
    selection_cli:
        CommandLine|contains|all:
            - call
            - uninstall
    condition: all of selection_*
ocsf_mapping:
    class_name: process_activity
    activity_id: 1
    logsource:
        category:
            source_field: category
            source_value: process_creation
            mapped_at: '2025-11-26T02:28:13.344377+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:28:13.344377+00:00'
    detection_fields:
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-11-26T02:28:13.344393+00:00'
        -   source_field: OriginalFileName
            target_table: process_activity
            target_field: process.file.name
            mapped_at: '2025-11-26T02:28:13.344395+00:00'
        -   source_field: CommandLine
            target_table: process_activity
            target_field: process.cmd_line
            mapped_at: '2025-11-26T02:28:13.344397+00:00'
