title: ESXi Syslog Configuration Change Via ESXCLI
id: 38eb1dbb-011f-40b1-a126-cf03a0210563
status: test
level: medium
author: Cedric Maurugeon
description: Detects changes to the ESXi syslog configuration via "esxcli"
references:
    - https://support.solarwinds.com/SuccessCenter/s/article/Configure-ESXi-Syslog-to-LEM?language=en_US
    - https://developer.broadcom.com/xapis/esxcli-command-reference/7.0.0/namespace/esxcli_system.html
falsepositives:
    - Legitimate administrative activities
tags:
    - attack.defense-evasion
    - attack.t1562.001
    - attack.t1562.003
date: '2023-09-04'
logsource:
    category: process_creation
    product: linux
detection:
    selection:
        Image|endswith: /esxcli
        CommandLine|contains|all:
            - system
            - syslog
            - config
        CommandLine|contains: ' set'
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: 1
    logsource:
        category:
            source_field: category
            source_value: process_creation
            mapped_at: '2025-12-04T01:36:52.070138+00:00'
        product:
            source_field: product
            source_value: linux
            mapped_at: '2025-12-04T01:36:52.070138+00:00'
    detection_fields:
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-12-04T01:36:52.070157+00:00'
        -   source_field: CommandLine
            target_table: process_activity
            target_field: process.cmd_line
            mapped_at: '2025-12-04T01:36:52.070159+00:00'
