id: b8b1b304-a60f-4999-9a6e-c547bde03ffd
title: DeviceCredentialDeployment Execution
status: test
level: medium
description: Detects the execution of DeviceCredentialDeployment to hide a process
    from view
author: Nasreddine Bencherchali (Nextron Systems)
date: '2022-08-19'
tags:
    - attack.defense-evasion
    - attack.t1218
references:
    - https://github.com/LOLBAS-Project/LOLBAS/pull/147
falsepositives:
    - Unlikely
taxonomy: sigma
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: \DeviceCredentialDeployment.exe
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: 1
    logsource:
        category:
            source_field: category
            source_value: process_creation
            mapped_at: '2025-11-26T02:28:35.344106+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:28:35.344106+00:00'
    detection_fields:
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-11-26T02:28:35.344131+00:00'
