id: 1f0f6176-6482-4027-b151-00071af39d7e
title: Arbitrary File Download Via ConfigSecurityPolicy.EXE
status: test
level: medium
description: 'Detects the execution of "ConfigSecurityPolicy.EXE", a binary part of
    Windows Defender used to manage settings in Windows Defender.

    Users can configure different pilot collections for each of the co-management
    workloads.

    It can be abused by attackers in order to upload or download files.

    '
author: frack113
date: '2021-11-26'
modified: '2022-05-16'
tags:
    - attack.exfiltration
    - attack.t1567
references:
    - https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
falsepositives:
    - Unknown
taxonomy: sigma
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        CommandLine|contains: ConfigSecurityPolicy.exe
        Image|endswith: \ConfigSecurityPolicy.exe
        OriginalFileName: ConfigSecurityPolicy.exe
    selection_url:
        CommandLine|contains:
            - ftp://
            - http://
            - https://
    condition: all of selection_*
ocsf_mapping:
    class_name: process_activity
    logsource:
        category:
            source_field: category
            source_value: process_creation
            mapped_at: '2025-11-13T20:20:48.432049+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:20:48.432049+00:00'
    detection_fields:
        -   source_field: CommandLine
            target_table: process_activity
            target_field: process.cmd_line
            mapped_at: '2025-11-13T20:20:48.432055+00:00'
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-11-13T20:20:48.432056+00:00'
        -   source_field: OriginalFileName
            target_table: process_activity
            target_field: process.file.name
            mapped_at: '2025-11-13T20:20:48.432058+00:00'
