id: a383dec4-deec-4e6e-913b-ed9249670848
title: Potential Signing Bypass Via Windows Developer Features
status: test
level: high
description: Detects when a user enable developer features such as "Developer Mode"
    or "Application Sideloading". Which allows the user to install untrusted packages.
author: Nasreddine Bencherchali (Nextron Systems)
date: '2023-01-11'
tags:
    - attack.defense-evasion
references:
    - Internal Research
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
falsepositives:
    - Unknown
related: 'SigmaRelated(related=[SigmaRelatedItem(id=UUID(''b110ebaf-697f-4da1-afd5-b536fa27a2c1''),
    type=<SigmaRelatedType.SIMILAR: 6>)])'
taxonomy: sigma
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        Image|endswith: \SystemSettingsAdminFlows.exe
        OriginalFileName: SystemSettingsAdminFlows.EXE
    selection_flag:
        CommandLine|contains: TurnOnDeveloperFeatures
    selection_options:
        CommandLine|contains:
            - DeveloperUnlock
            - EnableSideloading
    condition: all of selection_*
ocsf_mapping:
    class_name: process_activity
    logsource:
        category:
            source_field: category
            source_value: process_creation
            mapped_at: '2025-11-13T20:20:47.751580+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:20:47.751580+00:00'
    detection_fields:
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-11-13T20:20:47.751589+00:00'
        -   source_field: OriginalFileName
            target_table: process_activity
            target_field: process.file.name
            mapped_at: '2025-11-13T20:20:47.751592+00:00'
        -   source_field: CommandLine
            target_table: process_activity
            target_field: process.cmd_line
            mapped_at: '2025-11-13T20:20:47.751594+00:00'
