id: 16905e21-66ee-42fe-b256-1318ada2d770
title: Start of NT Virtual DOS Machine
status: test
level: medium
description: Ntvdm.exe allows the execution of 16-bit Windows applications on 32-bit
    Windows operating systems, as well as the execution of both 16-bit and 32-bit
    DOS applications
author: frack113
date: '2022-07-16'
modified: '2022-07-16'
tags:
    - attack.defense-evasion
references:
    - https://learn.microsoft.com/en-us/windows/compatibility/ntvdm-and-16-bit-app-support
    - https://support.microsoft.com/fr-fr/topic/an-ms-dos-based-program-that-uses-the-ms-dos-protected-mode-interface-crashes-on-a-computer-that-is-running-windows-7-5dc739ea-987b-b458-15e4-d28d5cca63c7
    - https://app.any.run/tasks/93fe92fa-8b2b-4d92-8c09-a841aed2e793/
    - https://app.any.run/tasks/214094a7-0abc-4a7b-a564-1b757faed79d/
falsepositives:
    - Legitimate use
taxonomy: sigma
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith:
            - \ntvdm.exe
            - \csrstub.exe
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: 1
    logsource:
        category:
            source_field: category
            source_value: process_creation
            mapped_at: '2025-11-26T02:27:29.456262+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:27:29.456262+00:00'
    detection_fields:
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-11-26T02:27:29.456284+00:00'
