title: HackTool - RedMimicry Winnti Playbook Execution
id: 95022b85-ff2a-49fa-939a-d7b8f56eeb9b
status: test
level: high
author: Alexander Rausch
description: Detects actions caused by the RedMimicry Winnti playbook a automated
    breach emulations utility
references:
    - https://redmimicry.com/posts/redmimicry-winnti/
falsepositives:
    - Unknown
tags:
    - attack.execution
    - attack.defense-evasion
    - attack.t1106
    - attack.t1059.003
    - attack.t1218.011
date: '2020-06-24'
modified: '2023-03-01'
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith:
            - \rundll32.exe
            - \cmd.exe
        CommandLine|contains:
            - gthread-3.6.dll
            - \Windows\Temp\tmp.bat
            - sigcmm-2.4.dll
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: 1
    logsource:
        category:
            source_field: category
            source_value: process_creation
            mapped_at: '2025-12-04T01:42:55.435077+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:42:55.435077+00:00'
    detection_fields:
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-12-04T01:42:55.435091+00:00'
        -   source_field: CommandLine
            target_table: process_activity
            target_field: process.cmd_line
            mapped_at: '2025-12-04T01:42:55.435093+00:00'
