id: bf344fea-d947-4ef4-9192-34d008315d3a
title: Suspicious Shim Database Patching Activity
status: test
level: high
description: Detects installation of new shim databases that try to patch sections
    of known processes for potential process injection or persistence.
author: Nasreddine Bencherchali (Nextron Systems)
date: '2023-08-01'
modified: '2023-12-06'
tags:
    - attack.persistence
    - attack.t1546.011
references:
    - https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/pillowmint-fin7s-monkey-thief/
    - https://www.fireeye.com/blog/threat-research/2017/05/fin7-shim-databases-persistence.html
falsepositives:
    - Unknown
taxonomy: sigma
logsource:
    category: registry_set
    product: windows
detection:
    selection:
        TargetObject|contains: \SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Custom\
        TargetObject|endswith:
            - \csrss.exe
            - \dllhost.exe
            - \explorer.exe
            - \RuntimeBroker.exe
            - \services.exe
            - \sihost.exe
            - \svchost.exe
            - \taskhostw.exe
            - \winlogon.exe
            - \WmiPrvSe.exe
    condition: selection
ocsf_mapping:
    class_name: null
    logsource:
        category:
            source_field: category
            source_value: registry_set
            mapped_at: null
        product:
            source_field: product
            source_value: windows
            mapped_at: null
    detection_fields:
        -   source_field: TargetObject
            target_table: null
            target_field: null
            mapped_at: null
