title: Outlook Security Settings Updated - Registry
id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
status: test
level: medium
author: frack113
description: Detects changes to the registry values related to outlook security settings
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1137/T1137.md
    - https://learn.microsoft.com/en-us/outlook/troubleshoot/security/information-about-email-security-settings
falsepositives:
    - Administrative activity
tags:
    - attack.persistence
    - attack.t1137
date: '2021-12-28'
modified: '2023-08-17'
logsource:
    category: registry_set
    product: windows
detection:
    selection:
        TargetObject|contains|all:
            - \SOFTWARE\Microsoft\Office\
            - \Outlook\Security\
    condition: selection
related:
    -   id: a166f74e-bf44-409d-b9ba-ea4b2dd8b3cd
        type: similar
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        category:
            source_field: category
            source_value: registry_set
            mapped_at: null
        product:
            source_field: product
            source_value: windows
            mapped_at: null
    detection_fields:
        -   source_field: TargetObject
            target_table: null
            target_field: null
            mapped_at: null
