id: 6db5eaf9-88f7-4ed9-af7d-9ef2ad12f236
title: Winget Admin Settings Modification
status: test
level: low
description: Detects changes to the AppInstaller (winget) admin settings. Such as
    enabling local manifest installations or disabling installer hash checks
author: Nasreddine Bencherchali (Nextron Systems)
date: '2023-04-17'
modified: '2023-08-17'
tags:
    - attack.defense-evasion
    - attack.persistence
references:
    - https://github.com/nasbench/Misc-Research/tree/b9596e8109dcdb16ec353f316678927e507a5b8d/LOLBINs/Winget
    - https://github.com/microsoft/winget-cli/blob/02d2f93807c9851d73eaacb4d8811a76b64b7b01/src/AppInstallerCommonCore/Public/winget/AdminSettings.h#L13
falsepositives:
    - The event doesn't contain information about the type of change. False positives
        are expected with legitimate changes
taxonomy: sigma
logsource:
    category: registry_set
    product: windows
detection:
    selection:
        Image|endswith: \winget.exe
        TargetObject|startswith: \REGISTRY\A\
        TargetObject|endswith: \LocalState\admin_settings
    condition: selection
ocsf_mapping:
    class_name: process_activity
    logsource:
        category:
            source_field: category
            source_value: registry_set
            mapped_at: '2025-11-13T20:22:05.938213+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:22:05.938213+00:00'
    detection_fields:
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-11-13T20:22:05.938223+00:00'
        -   source_field: TargetObject
            target_table: process_activity
            target_field: file.path
            mapped_at: '2025-11-13T20:22:05.938225+00:00'
