id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
title: Security Support Provider (SSP) Added to LSA Configuration
status: test
level: high
description: 'Detects the addition of a SSP to the registry. Upon a reboot or API
    call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.

    '
author: iwillkeepwatch
date: '2019-01-18'
modified: '2022-08-09'
tags:
    - attack.persistence
    - attack.t1547.005
references:
    - https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
    - https://github.com/EmpireProject/Empire/blob/08cbd274bef78243d7a8ed6443b8364acd1fc48b/data/module_source/persistence/Install-SSP.ps1#L157
falsepositives:
    - Unknown
taxonomy: sigma
logsource:
    category: registry_event
    product: windows
detection:
    selection:
        TargetObject|endswith:
            - \Control\Lsa\Security Packages
            - \Control\Lsa\OSConfig\Security Packages
    filter_main_msiexec:
        Image:
            - C:\Windows\system32\msiexec.exe
            - C:\Windows\syswow64\MsiExec.exe
    condition: selection and not 1 of filter_main_*
ocsf_mapping:
    class_name: process_activity
    logsource:
        category:
            source_field: category
            source_value: registry_event
            mapped_at: '2025-11-13T20:22:11.990626+00:00'
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:22:11.990626+00:00'
    detection_fields:
        -   source_field: TargetObject
            target_table: process_activity
            target_field: file.path
            mapped_at: '2025-11-13T20:22:11.990651+00:00'
        -   source_field: Image
            target_table: process_activity
            target_field: process.name
            mapped_at: '2025-11-13T20:22:11.990655+00:00'
