id: 0372e1f9-0fd2-40f7-be1b-a7b2b848fa7b
title: Disable Privacy Settings Experience in Registry
status: test
level: medium
description: Detects registry modifications that disable Privacy Settings Experience
author: frack113
date: '2022-10-02'
modified: '2023-08-17'
tags:
    - attack.defense-evasion
    - attack.t1562.001
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/9e5b12c4912c07562aec7500447b11fa3e17e254/atomics/T1562.001/T1562.001.md
falsepositives:
    - Legitimate admin script
taxonomy: sigma
logsource:
    category: registry_set
    product: windows
detection:
    selection:
        TargetObject|endswith: \SOFTWARE\Policies\Microsoft\Windows\OOBE\DisablePrivacyExperience
        Details: DWORD (0x00000000)
    condition: selection
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        category:
            source_field: category
            source_value: registry_set
            mapped_at: null
        product:
            source_field: product
            source_value: windows
            mapped_at: null
    detection_fields:
        -   source_field: TargetObject
            target_table: null
            target_field: null
            mapped_at: null
        -   source_field: Details
            target_table: null
            target_field: null
            mapped_at: null
