id: 60936b49-fca0-4f32-993d-7415edcf9a5d
title: New Application in AppCompat
status: test
level: informational
description: A General detection for a new application in AppCompat. This indicates
    an application executing for the first time on an endpoint.
author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
date: '2020-05-02'
modified: '2023-08-17'
tags:
    - attack.execution
    - attack.t1204.002
references:
    - https://github.com/OTRF/detection-hackathon-apt29/issues/1
    - https://github.com/OTRF/ThreatHunter-Playbook/blob/2d4257f630f4c9770f78d0c1df059f891ffc3fec/docs/evals/apt29/detections/1.A.1_DFD6A782-9BDB-4550-AB6B-525E825B095E.md
falsepositives:
    - This rule is to explore new applications on an endpoint. False positives depends
        on the organization.
    - Newly setup system.
    - Legitimate installation of new application.
taxonomy: sigma
logsource:
    category: registry_set
    product: windows
detection:
    selection:
        TargetObject|contains: \AppCompatFlags\Compatibility Assistant\Store\
    condition: selection
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        category:
            source_field: category
            source_value: registry_set
            mapped_at: null
        product:
            source_field: product
            source_value: windows
            mapped_at: null
    detection_fields:
        -   source_field: TargetObject
            target_table: null
            target_field: null
            mapped_at: null
