title: Sysmon Configuration Change
id: 8ac03a65-6c84-4116-acad-dc1558ff7a77
status: test
level: medium
author: frack113
description: Detects a Sysmon configuration change, which could be the result of a
    legitimate reconfiguration or someone trying manipulate the configuration
references:
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
falsepositives:
    - Legitimate administrative action
tags:
    - attack.defense-evasion
date: '2022-01-12'
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 16
    condition: selection
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: null
        service:
            source_field: service
            source_value: sysmon
            mapped_at: null
    detection_fields:
        -   source_field: EventID
            target_table: null
            target_field: null
            mapped_at: null
