title: ADCS Certificate Template Configuration Vulnerability with Risky EKU
id: bfbd3291-de87-4b7c-88a2-d6a5deb28668
status: test
level: high
author: Orlinum , BlueDefenZer
description: Detects certificate creation with template allowing risk permission subject
    and risky EKU
references:
    - https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
falsepositives:
    - Administrator activity
    - Proxy SSL certificate with subject modification
    - Smart card enrollement
tags:
    - attack.privilege-escalation
    - attack.credential-access
date: '2021-11-17'
modified: '2022-12-25'
logsource:
    product: windows
    service: security
    definition: Certificate services loaded a template would trigger event ID 4898
        and certificate Services template was updated would trigger event ID 4899.
        A risk permission seems to be coming if template contain specific flag with
        risky EKU.
detection:
    selection10:
        EventID: 4898
        TemplateContent|contains:
            - 1.3.6.1.5.5.7.3.2
            - 1.3.6.1.5.2.3.4
            - 1.3.6.1.4.1.311.20.2.2
            - 2.5.29.37.0
    selection11:
        TemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    selection20:
        EventID: 4899
        NewTemplateContent|contains:
            - 1.3.6.1.5.5.7.3.2
            - 1.3.6.1.5.2.3.4
            - 1.3.6.1.4.1.311.20.2.2
            - 2.5.29.37.0
    selection21:
        NewTemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    condition: (selection10 and selection11) or (selection20 and selection21)
ocsf_mapping:
    class_name: vulnerability_finding
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:55:37.914256+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-12-04T01:55:37.914256+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: vulnerability_finding
            target_field: metadata.event_code
            mapped_at: '2025-12-04T01:55:37.914292+00:00'
        -   source_field: TemplateContent
            target_table: vulnerability_finding
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:55:37.914296+00:00'
        -   source_field: NewTemplateContent
            target_table: vulnerability_finding
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:55:37.914298+00:00'
