id: bfbd3291-de87-4b7c-88a2-d6a5deb28668
title: ADCS Certificate Template Configuration Vulnerability with Risky EKU
status: test
level: high
description: Detects certificate creation with template allowing risk permission subject
    and risky EKU
author: Orlinum , BlueDefenZer
date: '2021-11-17'
modified: '2022-12-25'
tags:
    - attack.privilege-escalation
    - attack.credential-access
references:
    - https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
falsepositives:
    - Administrator activity
    - Proxy SSL certificate with subject modification
    - Smart card enrollement
taxonomy: sigma
logsource:
    product: windows
    service: security
    definition: Certificate services loaded a template would trigger event ID 4898
        and certificate Services template was updated would trigger event ID 4899.
        A risk permission seems to be coming if template contain specific flag with
        risky EKU.
detection:
    selection10:
        EventID: 4898
        TemplateContent|contains:
            - 1.3.6.1.5.5.7.3.2
            - 1.3.6.1.5.2.3.4
            - 1.3.6.1.4.1.311.20.2.2
            - 2.5.29.37.0
    selection11:
        TemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    selection20:
        EventID: 4899
        NewTemplateContent|contains:
            - 1.3.6.1.5.5.7.3.2
            - 1.3.6.1.5.2.3.4
            - 1.3.6.1.4.1.311.20.2.2
            - 2.5.29.37.0
    selection21:
        NewTemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    condition: (selection10 and selection11) or (selection20 and selection21)
ocsf_mapping:
    class_name: null
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: null
        service:
            source_field: service
            source_value: security
            mapped_at: null
    detection_fields:
        -   source_field: EventID
            target_table: null
            target_field: null
            mapped_at: null
        -   source_field: TemplateContent
            target_table: null
            target_field: null
            mapped_at: null
        -   source_field: NewTemplateContent
            target_table: null
            target_field: null
            mapped_at: null
