id: 898d5fc9-fbc3-43de-93ad-38e97237c344
title: Suspicious AppX Package Installation Attempt
status: test
level: medium
description: Detects an appx package installation with the error code "0x80073cff"
    which indicates that the package didn't meet the signing requirements and could
    be suspicious
author: Nasreddine Bencherchali (Nextron Systems)
date: '2023-01-11'
tags:
    - attack.defense-evasion
references:
    - Internal Research
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
    - https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
    - https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
falsepositives:
    - Legitimate AppX packages not signed by MS used part of an enterprise
taxonomy: sigma
logsource:
    product: windows
    service: appxdeployment-server
detection:
    selection:
        EventID: 401
        ErrorCode: '0x80073cff'
    condition: selection
ocsf_mapping:
    class_name: process_activity
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:24:52.859982+00:00'
        service:
            source_field: service
            source_value: appxdeployment-server
            mapped_at: '2025-11-13T20:24:52.859982+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-13T20:24:53.619088+00:00'
        -   source_field: ErrorCode
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-13T20:24:53.619109+00:00'
