id: 5ee3a654-372f-11ec-8d3d-0242ac130003
title: ADCS Certificate Template Configuration Vulnerability
status: test
level: low
description: Detects certificate creation with template allowing risk permission subject
author: Orlinum , BlueDefenZer
date: '2021-11-17'
modified: '2022-12-25'
tags:
    - attack.privilege-escalation
    - attack.credential-access
references:
    - https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
falsepositives:
    - Administrator activity
    - Proxy SSL certificate with subject modification
    - Smart card enrollement
taxonomy: sigma
logsource:
    product: windows
    service: security
    definition: Certificate services loaded a template would trigger event ID 4898
        and certificate Services template was updated would trigger event ID 4899.
        A risk permission seems to be coming if template contain specific flag.
detection:
    selection1:
        EventID: 4898
        TemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    selection2:
        EventID: 4899
        NewTemplateContent|contains: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
    condition: selection1 or selection2
ocsf_mapping:
    class_name: vulnerability_finding
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:45:15.420371+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-11-26T02:45:15.420371+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: vulnerability_finding
            target_field: metadata.event_code
            mapped_at: '2025-11-26T02:45:15.420385+00:00'
        -   source_field: TemplateContent
            target_table: vulnerability_finding
            target_field: <UNMAPPED>
            mapped_at: '2025-11-26T02:45:15.420387+00:00'
        -   source_field: NewTemplateContent
            target_table: vulnerability_finding
            target_field: <UNMAPPED>
            mapped_at: '2025-11-26T02:45:15.420388+00:00'
