id: cd0f7229-d16f-42de-8fe3-fba365fbcb3a
title: Invoke-Obfuscation Via Use Rundll32 - Security
status: test
level: high
description: Detects Obfuscated Powershell via use Rundll32 in Scripts
author: Nikita Nazarov, oscd.community
date: '2020-10-09'
modified: '2022-11-29'
tags:
    - attack.defense-evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
references:
    - https://github.com/SigmaHQ/sigma/issues/1009
falsepositives:
    - Unknown
related: 'SigmaRelated(related=[SigmaRelatedItem(id=UUID(''641a4bfb-c017-44f7-800c-2aee0184ce9b''),
    type=<SigmaRelatedType.DERIVED: 2>)])'
taxonomy: sigma
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    selection:
        EventID: 4697
        ServiceFileName|contains|all:
            - '&&'
            - rundll32
            - shell32.dll
            - shellexec_rundll
        ServiceFileName|contains:
            - value
            - invoke
            - comspec
            - iex
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: UNMAPPED
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:44:14.805894+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-11-26T02:44:14.805894+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-26T02:44:14.805918+00:00'
        -   source_field: ServiceFileName
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-26T02:44:14.805920+00:00'
