title: Invoke-Obfuscation Via Stdin - Security
id: 80b708f3-d034-40e4-a6c8-d23b7a7db3d1
status: test
level: high
author: Nikita Nazarov, oscd.community
description: Detects Obfuscated Powershell via Stdin in Scripts
references:
    - https://github.com/SigmaHQ/sigma/issues/1009
falsepositives:
    - Unknown
tags:
    - attack.defense-evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
date: '2020-10-12'
modified: '2022-11-29'
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    selection:
        EventID: 4697
        ServiceFileName|contains|all:
            - set
            - '&&'
        ServiceFileName|contains:
            - environment
            - invoke
            - ${input)
    condition: selection
related:
    -   id: 487c7524-f892-4054-b263-8a0ace63fc25
        type: derived
ocsf_mapping:
    class_name: process_activity
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:55:49.262387+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-12-04T01:55:49.262387+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-12-04T01:55:49.262408+00:00'
        -   source_field: ServiceFileName
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:55:49.262411+00:00'
