id: 4d7f1827-1637-4def-8d8a-fd254f9454df
title: Sysmon Application Crashed
status: test
level: high
description: Detects application popup reporting a failure of the Sysmon service
author: Tim Shelton
date: '2022-04-26'
modified: '2024-01-17'
tags:
    - attack.defense-evasion
    - attack.t1562
references:
    - https://github.com/nasbench/EVTX-ETW-Resources/blob/f1b010ce0ee1b71e3024180de1a3e67f99701fe4/ETWProvidersManifests/Windows10/1803/W10_1803_Pro_19700101_17134.1/WEPExplorer/Application%20Popup.xml#L36
falsepositives:
    - Unknown
taxonomy: sigma
logsource:
    product: windows
    service: system
detection:
    selection:
        Provider_Name: Application Popup
        EventID: 26
        Caption:
            - sysmon64.exe - Application Error
            - sysmon.exe - Application Error
    condition: selection
ocsf_mapping:
    class_name: process_activity
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:25:36.636451+00:00'
        service:
            source_field: service
            source_value: system
            mapped_at: '2025-11-13T20:25:36.636451+00:00'
    detection_fields:
        -   source_field: Provider_Name
            target_table: process_activity
            target_field: metadata.log_provider
            mapped_at: '2025-11-13T20:25:37.650917+00:00'
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-13T20:25:37.650932+00:00'
        -   source_field: Caption
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-13T20:25:37.650935+00:00'
