id: a3ab73f1-bd46-4319-8f06-4b20d0617886
title: Windows Defender Exploit Guard Tamper
status: test
level: high
description: 'Detects when someone is adding or removing applications or folders from
    exploit guard "ProtectedFolders" or "AllowedApplications"

    '
author: Nasreddine Bencherchali (Nextron Systems)
date: '2022-08-05'
modified: '2022-12-06'
tags:
    - attack.defense-evasion
    - attack.t1562.001
references:
    - https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/windows-10-controlled-folder-access-event-search/ba-p/2326088
falsepositives:
    - Unlikely
taxonomy: sigma
logsource:
    product: windows
    service: windefend
detection:
    allowed_apps_key:
        EventID: 5007
        NewValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
            Folder Access\AllowedApplications\
    allowed_apps_path:
        NewValue|contains:
            - \Users\Public\
            - \AppData\Local\Temp\
            - \Desktop\
            - \PerfLogs\
            - \Windows\Temp\
    protected_folders:
        EventID: 5007
        OldValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
            Folder Access\ProtectedFolders\
    condition: all of allowed_apps* or protected_folders
ocsf_mapping:
    class_name: process_activity
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:24:40.076829+00:00'
        service:
            source_field: service
            source_value: windefend
            mapped_at: '2025-11-13T20:24:40.076829+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-13T20:24:40.076874+00:00'
        -   source_field: NewValue
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-13T20:24:40.076878+00:00'
        -   source_field: OldValue
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-13T20:24:40.076881+00:00'
