title: Suspicious AppX Package Locations
id: 5cdeaf3d-1489-477c-95ab-c318559fc051
status: test
level: high
author: Nasreddine Bencherchali (Nextron Systems)
description: Detects an appx package added the pipeline of the "to be processed" packages
    which is located in suspicious locations
references:
    - Internal Research
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
    - https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
    - https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
falsepositives:
    - Unknown
tags:
    - attack.defense-evasion
date: '2023-01-11'
logsource:
    product: windows
    service: appxdeployment-server
detection:
    selection:
        EventID: 854
        Path|contains:
            - C:\Users\Public\
            - /users/public/
            - C:\PerfLogs\
            - C:/perflogs/
            - \Desktop\
            - /desktop/
            - \Downloads\
            - /Downloads/
            - C:\Windows\Temp\
            - C:/Windows/Temp/
            - \AppdData\Local\Temp\
            - /AppdData/Local/Temp/
    condition: selection
ocsf_mapping:
    class_name: scheduled_job_activity
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:56:41.956056+00:00'
        service:
            source_field: service
            source_value: appxdeployment-server
            mapped_at: '2025-12-04T01:56:41.956056+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: scheduled_job_activity
            target_field: metadata.event_code
            mapped_at: '2025-12-04T01:56:41.956070+00:00'
        -   source_field: Path
            target_table: scheduled_job_activity
            target_field: job.file.path
            mapped_at: '2025-12-04T01:56:41.956072+00:00'
