title: Windows Defender Exploit Guard Tamper
id: a3ab73f1-bd46-4319-8f06-4b20d0617886
status: test
level: high
author: Nasreddine Bencherchali (Nextron Systems)
description: 'Detects when someone is adding or removing applications or folders from
    exploit guard "ProtectedFolders" or "AllowedApplications"

    '
references:
    - https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/windows-10-controlled-folder-access-event-search/ba-p/2326088
falsepositives:
    - Unlikely
tags:
    - attack.defense-evasion
    - attack.t1562.001
date: '2022-08-05'
modified: '2022-12-06'
logsource:
    product: windows
    service: windefend
detection:
    allowed_apps_key:
        EventID: 5007
        NewValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
            Folder Access\AllowedApplications\
    allowed_apps_path:
        NewValue|contains:
            - \Users\Public\
            - \AppData\Local\Temp\
            - \Desktop\
            - \PerfLogs\
            - \Windows\Temp\
    protected_folders:
        EventID: 5007
        OldValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
            Folder Access\ProtectedFolders\
    condition: all of allowed_apps* or protected_folders
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: null
        service:
            source_field: service
            source_value: windefend
            mapped_at: null
    detection_fields:
        -   source_field: EventID
            target_table: null
            target_field: null
            mapped_at: null
        -   source_field: NewValue
            target_table: null
            target_field: null
            mapped_at: null
        -   source_field: OldValue
            target_table: null
            target_field: null
            mapped_at: null
