id: 13fc89a9-971e-4ca6-b9dc-aa53a445bf40
title: DHCP Server Loaded the CallOut DLL
status: test
level: high
description: This rule detects a DHCP server in which a specified Callout DLL (in
    registry) was loaded
author: Dimitrios Slamaris
date: '2017-05-15'
modified: '2022-12-25'
tags:
    - attack.defense-evasion
    - attack.t1574.002
references:
    - https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
    - https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
    - https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx
falsepositives:
    - Unknown
taxonomy: sigma
logsource:
    product: windows
    service: system
detection:
    selection:
        EventID: 1033
        Provider_Name: Microsoft-Windows-DHCP-Server
    condition: selection
ocsf_mapping:
    class_name: process_activity
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:25:33.762194+00:00'
        service:
            source_field: service
            source_value: system
            mapped_at: '2025-11-13T20:25:33.762194+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-13T20:25:33.762205+00:00'
        -   source_field: Provider_Name
            target_table: process_activity
            target_field: metadata.log_provider
            mapped_at: '2025-11-13T20:25:33.762207+00:00'
