id: dcf2db1f-f091-425b-a821-c05875b8925a
title: Invoke-Obfuscation VAR+ Launcher - Security
status: test
level: high
description: Detects Obfuscated use of Environment Variables to execute PowerShell
author: Jonathan Cheong, oscd.community
date: '2020-10-15'
modified: '2022-11-29'
tags:
    - attack.defense-evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
references:
    - https://github.com/SigmaHQ/sigma/issues/1009
falsepositives:
    - Unknown
related: 'SigmaRelated(related=[SigmaRelatedItem(id=UUID(''8ca7004b-e620-4ecb-870e-86129b5b8e75''),
    type=<SigmaRelatedType.DERIVED: 2>)])'
taxonomy: sigma
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    selection:
        EventID: 4697
        ServiceFileName|contains|all:
            - cmd
            - '"set'
            - -f
        ServiceFileName|contains:
            - /c
            - /r
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:45:16.103214+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-11-26T02:45:16.103214+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-26T02:45:16.103231+00:00'
        -   source_field: ServiceFileName
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-26T02:45:16.103233+00:00'
