title: Application Uninstalled
id: 570ae5ec-33dc-427c-b815-db86228ad43e
status: test
level: low
author: frack113
description: An application has been removed. Check if it is critical.
references:
    - https://github.com/nasbench/EVTX-ETW-Resources/blob/f1b010ce0ee1b71e3024180de1a3e67f99701fe4/ETWProvidersManifests/Windows11/22H2/W11_22H2_Pro_20221220_22621.963/WEPExplorer/Microsoft-Windows-MsiServer.xml
    - https://learn.microsoft.com/en-us/windows/win32/msi/event-logging
falsepositives:
    - Unknown
tags:
    - attack.impact
    - attack.t1489
date: '2022-01-28'
modified: '2022-09-17'
logsource:
    product: windows
    service: application
detection:
    selection:
        Provider_Name: MsiInstaller
        EventID:
            - 1034
            - 11724
    condition: selection
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: null
        service:
            source_field: service
            source_value: application
            mapped_at: null
    detection_fields:
        -   source_field: Provider_Name
            target_table: null
            target_field: null
            mapped_at: null
        -   source_field: EventID
            target_table: null
            target_field: null
            mapped_at: null
