id: 04b60639-39c0-412a-9fbe-e82499c881a3
title: Windows Defender Firewall Has Been Reset To Its Default Configuration
status: test
level: low
description: Detects activity when Windows Defender Firewall has been reset to its
    default configuration
author: frack113
date: '2022-02-19'
modified: '2023-04-21'
tags:
    - attack.defense-evasion
    - attack.t1562.004
references:
    - https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd364427(v=ws.10)
taxonomy: sigma
logsource:
    product: windows
    service: firewall-as
detection:
    selection:
        EventID:
            - 2032
            - 2060
    condition: selection
ocsf_mapping:
    class_name: process_activity
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:22:18.539668+00:00'
        service:
            source_field: service
            source_value: firewall-as
            mapped_at: '2025-11-13T20:22:18.539668+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-13T20:22:18.539678+00:00'
