title: DHCP Server Error Failed Loading the CallOut DLL
id: 75edd3fd-7146-48e5-9848-3013d7f0282c
status: test
level: high
author: Dimitrios Slamaris, @atc_project (fix)
description: This rule detects a DHCP server error in which a specified Callout DLL
    (in registry) could not be loaded
references:
    - https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
    - https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
    - https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx
falsepositives:
    - Unknown
tags:
    - attack.defense-evasion
    - attack.t1574.002
date: '2017-05-15'
modified: '2022-12-25'
logsource:
    product: windows
    service: system
detection:
    selection:
        EventID:
            - 1031
            - 1032
            - 1034
        Provider_Name: Microsoft-Windows-DHCP-Server
    condition: selection
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: null
        service:
            source_field: service
            source_value: system
            mapped_at: null
    detection_fields:
        -   source_field: EventID
            target_table: null
            target_field: null
            mapped_at: null
        -   source_field: Provider_Name
            target_table: null
            target_field: null
            mapped_at: null
