id: 1321dc4e-a1fe-481d-a016-52c45f0c8b4f
title: Windows Defender Exclusions Added
status: stable
level: medium
description: Detects the Setting of Windows Defender Exclusions
author: Christian Burkard (Nextron Systems)
date: '2021-07-06'
modified: '2022-12-06'
tags:
    - attack.defense-evasion
    - attack.t1562.001
references:
    - https://twitter.com/_nullbind/status/1204923340810543109
falsepositives:
    - Administrator actions
taxonomy: sigma
logsource:
    product: windows
    service: windefend
detection:
    selection:
        EventID: 5007
        NewValue|contains: \Microsoft\Windows Defender\Exclusions
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: UNMAPPED
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:47:15.340744+00:00'
        service:
            source_field: service
            source_value: windefend
            mapped_at: '2025-11-26T02:47:15.340744+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-26T02:47:15.340772+00:00'
        -   source_field: NewValue
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-26T02:47:15.340776+00:00'
