id: 80b708f3-d034-40e4-a6c8-d23b7a7db3d1
title: Invoke-Obfuscation Via Stdin - Security
status: test
level: high
description: Detects Obfuscated Powershell via Stdin in Scripts
author: Nikita Nazarov, oscd.community
date: '2020-10-12'
modified: '2022-11-29'
tags:
    - attack.defense-evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
references:
    - https://github.com/SigmaHQ/sigma/issues/1009
falsepositives:
    - Unknown
related: 'SigmaRelated(related=[SigmaRelatedItem(id=UUID(''487c7524-f892-4054-b263-8a0ace63fc25''),
    type=<SigmaRelatedType.DERIVED: 2>)])'
taxonomy: sigma
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    selection:
        EventID: 4697
        ServiceFileName|contains|all:
            - set
            - '&&'
        ServiceFileName|contains:
            - environment
            - invoke
            - ${input)
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: UNMAPPED
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-26T02:45:22.933406+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-11-26T02:45:22.933406+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-26T02:45:22.933420+00:00'
        -   source_field: ServiceFileName
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-11-26T02:45:22.933422+00:00'
