title: Windows Defender Firewall Has Been Reset To Its Default Configuration
id: 04b60639-39c0-412a-9fbe-e82499c881a3
status: test
level: low
author: frack113
description: Detects activity when Windows Defender Firewall has been reset to its
    default configuration
references:
    - https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd364427(v=ws.10)
tags:
    - attack.defense-evasion
    - attack.t1562.004
date: '2022-02-19'
modified: '2023-04-21'
logsource:
    product: windows
    service: firewall-as
detection:
    selection:
        EventID:
            - 2032
            - 2060
    condition: selection
ocsf_mapping:
    class_name: null
    activity_id: null
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: null
        service:
            source_field: service
            source_value: firewall-as
            mapped_at: null
    detection_fields:
        -   source_field: EventID
            target_table: null
            target_field: null
            mapped_at: null
