id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
title: Invoke-Obfuscation STDIN+ Launcher - Security
status: test
level: high
description: Detects Obfuscated use of stdin to execute PowerShell
author: Jonathan Cheong, oscd.community
date: '2020-10-15'
modified: '2022-11-29'
tags:
    - attack.defense-evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
references:
    - https://github.com/SigmaHQ/sigma/issues/1009
falsepositives:
    - Unknown
related: 'SigmaRelated(related=[SigmaRelatedItem(id=UUID(''72862bf2-0eb1-11eb-adc1-0242ac120002''),
    type=<SigmaRelatedType.DERIVED: 2>)])'
taxonomy: sigma
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    selection:
        EventID: 4697
        ServiceFileName|contains|all:
            - cmd
            - powershell
    selection2:
        ServiceFileName|contains:
            - ${input}
            - noexit
    selection3:
        ServiceFileName|contains:
            - ' /c '
            - ' /r '
    condition: all of selection*
ocsf_mapping:
    class_name: process_activity
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-11-13T20:23:44.009579+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-11-13T20:23:44.009579+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-11-13T20:23:44.009598+00:00'
        -   source_field: ServiceFileName
            target_table: process_activity
            target_field: process.file.name
            mapped_at: '2025-11-13T20:23:44.009601+00:00'
