title: Invoke-Obfuscation Obfuscated IEX Invocation - Security
id: fd0f5778-d3cb-4c9a-9695-66759d04702a
status: test
level: high
author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
description: Detects all variations of obfuscated powershell IEX invocation code generated
    by Invoke-Obfuscation framework from the code block linked in the references
references:
    - https://github.com/danielbohannon/Invoke-Obfuscation/blob/f20e7f843edd0a3a7716736e9eddfa423395dd26/Out-ObfuscatedStringCommand.ps1#L873-L888
falsepositives:
    - Unknown
tags:
    - attack.defense-evasion
    - attack.t1027
date: '2019-11-08'
modified: '2022-11-27'
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    selection_eid:
        EventID: 4697
    selection_servicefilename:
        ServiceFileName|re|all:
            - \$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[
            - \$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[
            - \$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[
            - \$env:ComSpec\[(\s*\d{1,3}\s*,){2}
            - \\*mdr\*\W\s*\)\.Name
            - \$VerbosePreference\.ToString\(
        ServiceFileName|re: \String\]\s*\$VerbosePreference
    condition: all of selection_*
related:
    -   id: 51aa9387-1c53-4153-91cc-d73c59ae1ca9
        type: derived
ocsf_mapping:
    class_name: process_activity
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:55:27.255628+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-12-04T01:55:27.255628+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-12-04T01:55:27.255647+00:00'
        -   source_field: ServiceFileName
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:55:27.255651+00:00'
