title: Windows Defender Exclusions Added
id: 1321dc4e-a1fe-481d-a016-52c45f0c8b4f
status: stable
level: medium
author: Christian Burkard (Nextron Systems)
description: Detects the Setting of Windows Defender Exclusions
references:
    - https://twitter.com/_nullbind/status/1204923340810543109
falsepositives:
    - Administrator actions
tags:
    - attack.defense-evasion
    - attack.t1562.001
date: '2021-07-06'
modified: '2022-12-06'
logsource:
    product: windows
    service: windefend
detection:
    selection:
        EventID: 5007
        NewValue|contains: \Microsoft\Windows Defender\Exclusions
    condition: selection
ocsf_mapping:
    class_name: process_activity
    activity_id: <UNMAPPED>
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:56:33.872837+00:00'
        service:
            source_field: service
            source_value: windefend
            mapped_at: '2025-12-04T01:56:33.872837+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-12-04T01:56:33.872855+00:00'
        -   source_field: NewValue
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:56:33.872857+00:00'
