title: Invoke-Obfuscation RUNDLL LAUNCHER - Security
id: f241cf1b-3a6b-4e1a-b4f9-133c00dd95ca
status: test
level: medium
author: Timur Zinniatullin, oscd.community
description: Detects Obfuscated Powershell via RUNDLL LAUNCHER
references:
    - https://github.com/SigmaHQ/sigma/issues/1009
falsepositives:
    - Unknown
tags:
    - attack.defense-evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
date: '2020-10-18'
modified: '2022-11-29'
logsource:
    product: windows
    service: security
    definition: The 'System Security Extension' audit subcategory need to be enabled
        to log the EID 4697
detection:
    selection:
        EventID: 4697
        ServiceFileName|contains|all:
            - rundll32.exe
            - shell32.dll
            - shellexec_rundll
            - powershell
    condition: selection
related:
    -   id: 11b52f18-aaec-4d60-9143-5dd8cc4706b9
        type: derived
ocsf_mapping:
    class_name: process_activity
    activity_id: 1
    logsource:
        product:
            source_field: product
            source_value: windows
            mapped_at: '2025-12-04T01:56:14.068709+00:00'
        service:
            source_field: service
            source_value: security
            mapped_at: '2025-12-04T01:56:14.068709+00:00'
    detection_fields:
        -   source_field: EventID
            target_table: process_activity
            target_field: metadata.event_code
            mapped_at: '2025-12-04T01:56:14.068722+00:00'
        -   source_field: ServiceFileName
            target_table: process_activity
            target_field: <UNMAPPED>
            mapped_at: '2025-12-04T01:56:14.068724+00:00'
